### ISSUE TITLE
Enable URL Rewriting problem

### ISSUE THREAD

**Issue by Leinad4Mind** [PGreca/pgsocial#14]
If Enable URL Rewriting is disabled at ACP, the username link redirects to: 
"mywebsite.com/memberlist.php?mode=viewprofile&u=2" instead of 
"mywebsite.com/forum/memberlist.php?mode=viewprofile&u=2"

**Comment by PGreca** [comment]
Can you explain me the setting you have disabled?

**Comment by Leinad4Mind** [comment]
Go to ACP - server configuration - server settings and disabled "Enable URL Rewriting" option.
