### ISSUE TITLE
install_pg_social_01 migration with missing column

### ISSUE THREAD

**Issue by Leinad4Mind** [PGreca/pgsocial#15]
pg_social_photos doesnt have photo_privacy column and therefore we get: 

`SQL ERROR [ mysqli ]

Unknown column 'photo_privacy' in 'field list' [1054]

SQL

SELECT photo_id, photo_file, photo_where, photo_privacy, user_id FROM phpbb_pg_social_photos WHERE user_id = '2' AND photo_where = '0' ORDER BY photo_time DESC LIMIT 0, 9

BACKTRACE`

**Comment by PGreca** [comment]
Resolved
