### ISSUE TITLE
I found a very strange bug that breaks phpbb. (Urgent Fix Req)

### ISSUE THREAD

**Issue by phxinternational** [PGreca/pgsocial#44]
Yes I cleared everything, cache and all the rest. I have uploaded all the latest files from your github and I have come across an very strange error that breaks the forum.

As admin if I send a friend request it works fine. But if a registered user tries to add someone as a friend the screen goes white and all you see is a message that says... REQUEST_SEND

That really needs fixing as it freezes everything up.

**Comment by phxinternational** [comment]
Update: This problem only seems to be in Internet explorer.. friend request works fine both ends on google chrome. I am going to test other browsers out shortly.

I can't seem to find where it breaks for IE.

**Comment by phxinternational** [comment]
Also breaks on firefox and opera browsers. The friend request does send, but members need to hit the back button and then refresh on their browsers... hopefully this can be fixed asap.

**Comment by PGreca** [comment]
Ok i will check this problem.
