### ISSUE TITLE
Album managing

### ISSUE THREAD

**Issue by Aspie96** [PGreca/pgsocial#7]
The user doesn't have many options when managing an album.
In particular, it should be possible to delete an album and to pick privacy settings for each photo (now it is just friends).
Also, each photo should maybe come with a description.

**Comment by PGreca** [comment]
1) Added setting privacy for personal albums. (Wall, Avatar and Cover will not have privacy, and only photos of "wall" album will have personal privacy).

**Comment by Aspie96** [comment]
I will mark it as closed because I assume that's the way you want it to be (with privacy settings only for albums).
Thanks!
